[workspace]
resolver = "2"
license = "GPL-3.0-or-later"
members = [
    "crates/morsh-crypto",
    "crates/morsh-proto",
    "crates/morsh-terminal",
    "crates/morsh-network",
    "crates/morsh-statesync",
    "crates/morsh-client",
    "crates/morsh-server",
    "crates/morsh-wrapper",
    "crates/morsh-prediction",
]
